{
 "title": "Kubernetes / Cost / Cluster",
 "tags": [ "loft-grafana-dashboard" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "core_cost_per_hour", "query": "0.027" },
   { "name": "mem_gig_cost_per_hour", "query": "0.013" }
  ]
 },
 "panels": [
  { "title": "Headlines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Cost Per Hour $",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) * $core_cost_per_hour + sum(container_memory_working_set_bytes{container!=\"\", image!=\"\"}) / 1024 / 1024 / 1024 * $mem_gig_cost_per_hour"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{container!=\"\"}) / 1024 / 1024"
    }
   ]
  },
  { "title": "Cost Per Account", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total Cost Per Hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels) by (label_kiosk_sh_account) * $core_cost_per_hour + sum(sum(container_memory_working_set_bytes{container!=\"\", image!=\"\"}) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels) by (label_kiosk_sh_account) / 1024 / 1024 / 1024 * $mem_gig_cost_per_hour",
     "legendFormat": "{{label_kiosk_sh_account}}"
    }
   ]
  },
  { "title": "Cost Per Account Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total Cost",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_namespace_labels{label_kiosk_sh_account!=\"\"}) by (label_kiosk_sh_account)"
    },
    {
     "expr": "sum(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account!=\"\"}) by (label_kiosk_sh_account) * $core_cost_per_hour + sum(sum(container_memory_working_set_bytes{container!=\"\", image!=\"\"}) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels) by (label_kiosk_sh_account) / 1024 / 1024 / 1024 * $mem_gig_cost_per_hour"
    },
    {
     "expr": "sum(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account!=\"\"}) by (label_kiosk_sh_account)"
    },
    {
     "expr": "sum(sum(container_memory_working_set_bytes{container!=\"\", image!=\"\"}) by (namespace) * on(namespace) group_left(label_kiosk_sh_account) kube_namespace_labels{label_kiosk_sh_account!=\"\"}) by (label_kiosk_sh_account) / 1024 / 1024"
    }
   ]
  },
  { "title": "Cost Per Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Total Cost Per Hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) * $core_cost_per_hour + sum(container_memory_working_set_bytes{container!=\"\", image!=\"\"}) by (namespace) / 1024 / 1024 / 1024 * $mem_gig_cost_per_hour",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Cost Per Namespace Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Total Cost",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_owner) by (namespace)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) * $core_cost_per_hour + sum(container_memory_working_set_bytes{container!=\"\", image!=\"\"}) by (namespace) / 1024 / 1024 / 1024 * $mem_gig_cost_per_hour"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\", image!=\"\"}) by (namespace) / 1024 / 1024"
    }
   ]
  }
 ]
}